version: '3.9'
services:

  app:
    env_file:
      - ./backend/stage.dev.env
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3001:3001
      - 3002:3002
    networks:
      - ft_network
    volumes:
      - ./backend/src:/app/src

  database:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - ft_network
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  front:
    depends_on:
      - app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    networks:
      - ft_network

networks:
  ft_network:
  